# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mpi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 736)
        MainWindow.setMinimumSize(QtCore.QSize(766, 690))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 761, 611))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupDeep = QtWidgets.QGroupBox(self.tab)
        self.groupDeep.setGeometry(QtCore.QRect(0, 0, 161, 251))
        self.groupDeep.setObjectName("groupDeep")
        self.apical = QtWidgets.QCheckBox(self.groupDeep)
        self.apical.setGeometry(QtCore.QRect(30, 40, 73, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.apical.setFont(font)
        self.apical.setObjectName("apical")
        self.mid = QtWidgets.QCheckBox(self.groupDeep)
        self.mid.setGeometry(QtCore.QRect(30, 70, 73, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.mid.setFont(font)
        self.mid.setObjectName("mid")
        self.basal = QtWidgets.QCheckBox(self.groupDeep)
        self.basal.setGeometry(QtCore.QRect(30, 100, 73, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.basal.setFont(font)
        self.basal.setObjectName("basal")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(170, 10, 241, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("3618.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupStatus = QtWidgets.QGroupBox(self.tab)
        self.groupStatus.setGeometry(QtCore.QRect(420, 0, 221, 241))
        self.groupStatus.setObjectName("groupStatus")
        self.layoutWidget = QtWidgets.QWidget(self.groupStatus)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 207, 170))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Reversible = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Reversible.setFont(font)
        self.Reversible.setObjectName("Reversible")
        self.verticalLayout.addWidget(self.Reversible)
        self.Partial = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Partial.setFont(font)
        self.Partial.setChecked(True)
        self.Partial.setObjectName("Partial")
        self.verticalLayout.addWidget(self.Partial)
        self.Irreversible = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Irreversible.setFont(font)
        self.Irreversible.setObjectName("Irreversible")
        self.verticalLayout.addWidget(self.Irreversible)
        self.RR = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RR.setFont(font)
        self.RR.setObjectName("RR")
        self.verticalLayout.addWidget(self.RR)
        self.Attenuation = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Attenuation.setFont(font)
        self.Attenuation.setObjectName("Attenuation")
        self.verticalLayout.addWidget(self.Attenuation)
        self.Hypokinesia = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Hypokinesia.setFont(font)
        self.Hypokinesia.setObjectName("Hypokinesia")
        self.verticalLayout.addWidget(self.Hypokinesia)
        self.Addlesion = QtWidgets.QPushButton(self.tab)
        self.Addlesion.setGeometry(QtCore.QRect(640, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Addlesion.setFont(font)
        self.Addlesion.setObjectName("Addlesion")
        self.CleanL = QtWidgets.QPushButton(self.tab)
        self.CleanL.setGeometry(QtCore.QRect(640, 100, 111, 51))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CleanL.setFont(font)
        self.CleanL.setObjectName("CleanL")
        self.groupStatus_2 = QtWidgets.QGroupBox(self.tab)
        self.groupStatus_2.setGeometry(QtCore.QRect(0, 250, 371, 181))
        self.groupStatus_2.setObjectName("groupStatus_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupStatus_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 131, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ant = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_ant.setFont(font)
        self.label_ant.setObjectName("label_ant")
        self.verticalLayout_2.addWidget(self.label_ant)
        self.label_sep = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_sep.setFont(font)
        self.label_sep.setObjectName("label_sep")
        self.verticalLayout_2.addWidget(self.label_sep)
        self.label_inf = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_inf.setFont(font)
        self.label_inf.setObjectName("label_inf")
        self.verticalLayout_2.addWidget(self.label_inf)
        self.label_lat = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_lat.setFont(font)
        self.label_lat.setObjectName("label_lat")
        self.verticalLayout_2.addWidget(self.label_lat)
        self.label_ap = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_ap.setFont(font)
        self.label_ap.setObjectName("label_ap")
        self.verticalLayout_2.addWidget(self.label_ap)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupStatus_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 20, 211, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Ant = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Ant.setFont(font)
        self.Ant.setObjectName("Ant")
        self.Ant.addItem("")
        self.Ant.addItem("")
        self.Ant.addItem("")
        self.Ant.addItem("")
        self.Ant.addItem("")
        self.verticalLayout_3.addWidget(self.Ant)
        self.Sep = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Sep.setFont(font)
        self.Sep.setObjectName("Sep")
        self.Sep.addItem("")
        self.Sep.addItem("")
        self.Sep.addItem("")
        self.Sep.addItem("")
        self.Sep.addItem("")
        self.verticalLayout_3.addWidget(self.Sep)
        self.Inf = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Inf.setFont(font)
        self.Inf.setObjectName("Inf")
        self.Inf.addItem("")
        self.Inf.addItem("")
        self.Inf.addItem("")
        self.Inf.addItem("")
        self.Inf.addItem("")
        self.verticalLayout_3.addWidget(self.Inf)
        self.Lat = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Lat.setFont(font)
        self.Lat.setObjectName("Lat")
        self.Lat.addItem("")
        self.Lat.addItem("")
        self.Lat.addItem("")
        self.Lat.addItem("")
        self.Lat.addItem("")
        self.verticalLayout_3.addWidget(self.Lat)
        self.AP = QtWidgets.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AP.setFont(font)
        self.AP.setObjectName("AP")
        self.AP.addItem("")
        self.AP.addItem("")
        self.AP.addItem("")
        self.AP.addItem("")
        self.AP.addItem("")
        self.verticalLayout_3.addWidget(self.AP)
        self.groupFun = QtWidgets.QGroupBox(self.tab)
        self.groupFun.setGeometry(QtCore.QRect(380, 260, 361, 171))
        self.groupFun.setObjectName("groupFun")
        self.Tl201 = QtWidgets.QRadioButton(self.groupFun)
        self.Tl201.setGeometry(QtCore.QRect(20, 20, 83, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tl201.setFont(font)
        self.Tl201.setAutoExclusive(True)
        self.Tl201.setObjectName("Tl201")
        self.MiBi = QtWidgets.QRadioButton(self.groupFun)
        self.MiBi.setGeometry(QtCore.QRect(110, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MiBi.setFont(font)
        self.MiBi.setAutoExclusive(True)
        self.MiBi.setObjectName("MiBi")
        self.label_7 = QtWidgets.QLabel(self.groupFun)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupFun)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupFun)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 141, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupFun)
        self.label_10.setGeometry(QtCore.QRect(150, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupFun)
        self.label_11.setGeometry(QtCore.QRect(220, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupFun)
        self.label_12.setGeometry(QtCore.QRect(290, 40, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.LVD = QtWidgets.QCheckBox(self.groupFun)
        self.LVD.setGeometry(QtCore.QRect(240, 140, 111, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LVD.setFont(font)
        self.LVD.setObjectName("LVD")
        self.SEF = QtWidgets.QLineEdit(self.groupFun)
        self.SEF.setGeometry(QtCore.QRect(140, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SEF.setFont(font)
        self.SEF.setText("")
        self.SEF.setObjectName("SEF")
        self.REF = QtWidgets.QLineEdit(self.groupFun)
        self.REF.setGeometry(QtCore.QRect(210, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.REF.setFont(font)
        self.REF.setText("")
        self.REF.setObjectName("REF")
        self.SLH = QtWidgets.QLineEdit(self.groupFun)
        self.SLH.setGeometry(QtCore.QRect(140, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.SLH.setFont(font)
        self.SLH.setText("")
        self.SLH.setObjectName("SLH")
        self.RLH = QtWidgets.QLineEdit(self.groupFun)
        self.RLH.setGeometry(QtCore.QRect(210, 90, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.RLH.setFont(font)
        self.RLH.setText("")
        self.RLH.setObjectName("RLH")
        self.Ext = QtWidgets.QLineEdit(self.groupFun)
        self.Ext.setGeometry(QtCore.QRect(150, 130, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Ext.setFont(font)
        self.Ext.setObjectName("Ext")
        self.Tid = QtWidgets.QLineEdit(self.groupFun)
        self.Tid.setGeometry(QtCore.QRect(280, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Tid.setFont(font)
        self.Tid.setObjectName("Tid")
        self.Comm = QtWidgets.QTextEdit(self.tab)
        self.Comm.setGeometry(QtCore.QRect(10, 440, 571, 131))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Comm.setFont(font)
        self.Comm.setObjectName("Comm")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(590, 440, 151, 131))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AddF = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AddF.setFont(font)
        self.AddF.setObjectName("AddF")
        self.verticalLayout_4.addWidget(self.AddF)
        self.CleanA = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CleanA.setFont(font)
        self.CleanA.setObjectName("CleanA")
        self.verticalLayout_4.addWidget(self.CleanA)
        self.Load = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Load.setFont(font)
        self.Load.setObjectName("Load")
        self.verticalLayout_4.addWidget(self.Load)
        self.Send = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Send.setFont(font)
        self.Send.setObjectName("Send")
        self.verticalLayout_4.addWidget(self.Send)
        self.groupWall = QtWidgets.QGroupBox(self.tab)
        self.groupWall.setGeometry(QtCore.QRect(160, 0, 261, 251))
        self.groupWall.setObjectName("groupWall")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_6.setGeometry(QtCore.QRect(180, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setAutoFillBackground(True)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_10.setGeometry(QtCore.QRect(40, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setAutoFillBackground(True)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_11.setGeometry(QtCore.QRect(30, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setAutoFillBackground(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_4.setGeometry(QtCore.QRect(110, 120, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setAutoFillBackground(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_7.setGeometry(QtCore.QRect(190, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setAutoFillBackground(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_9.setGeometry(QtCore.QRect(110, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setAutoFillBackground(True)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_8.setGeometry(QtCore.QRect(180, 170, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setAutoFillBackground(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_12.setGeometry(QtCore.QRect(40, 170, 51, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setAutoFillBackground(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupWall)
        self.checkBox_5.setGeometry(QtCore.QRect(110, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setAutoFillBackground(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.label.raise_()
        self.groupWall.raise_()
        self.groupDeep.raise_()
        self.groupStatus.raise_()
        self.Addlesion.raise_()
        self.CleanL.raise_()
        self.groupStatus_2.raise_()
        self.groupFun.raise_()
        self.Comm.raise_()
        self.layoutWidget.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tracerDose = QtWidgets.QGroupBox(self.tab_2)
        self.tracerDose.setGeometry(QtCore.QRect(10, 0, 361, 161))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.tracerDose.setFont(font)
        self.tracerDose.setObjectName("tracerDose")
        self.BW = QtWidgets.QLineEdit(self.tracerDose)
        self.BW.setGeometry(QtCore.QRect(140, 20, 71, 31))
        self.BW.setObjectName("BW")
        self.RMibiDose = QtWidgets.QLineEdit(self.tracerDose)
        self.RMibiDose.setGeometry(QtCore.QRect(130, 70, 61, 31))
        self.RMibiDose.setObjectName("RMibiDose")
        self.RRMibiDose = QtWidgets.QLineEdit(self.tracerDose)
        self.RRMibiDose.setGeometry(QtCore.QRect(290, 70, 61, 31))
        self.RRMibiDose.setObjectName("RRMibiDose")
        self.SMibiDose = QtWidgets.QLineEdit(self.tracerDose)
        self.SMibiDose.setGeometry(QtCore.QRect(130, 110, 61, 31))
        self.SMibiDose.setObjectName("SMibiDose")
        self.RSMibiDose = QtWidgets.QLineEdit(self.tracerDose)
        self.RSMibiDose.setGeometry(QtCore.QRect(290, 110, 61, 31))
        self.RSMibiDose.setObjectName("RSMibiDose")
        self.label_5 = QtWidgets.QLabel(self.tracerDose)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tracerDose)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.tracerDose)
        self.label_13.setGeometry(QtCore.QRect(10, 110, 111, 41))
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tracerDose)
        self.label_14.setGeometry(QtCore.QRect(200, 80, 91, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tracerDose)
        self.label_15.setGeometry(QtCore.QRect(200, 120, 91, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tracerDose)
        self.label_16.setGeometry(QtCore.QRect(220, 30, 31, 20))
        self.label_16.setObjectName("label_16")
        self.stressVitalSign = QtWidgets.QGroupBox(self.tab_2)
        self.stressVitalSign.setGeometry(QtCore.QRect(380, 0, 371, 161))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.stressVitalSign.setFont(font)
        self.stressVitalSign.setObjectName("stressVitalSign")
        self.label_22 = QtWidgets.QLabel(self.stressVitalSign)
        self.label_22.setGeometry(QtCore.QRect(200, 20, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.RichText)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.stressVitalSign)
        self.label_23.setGeometry(QtCore.QRect(280, 20, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.RichText)
        self.label_23.setObjectName("label_23")
        self.layoutWidget4 = QtWidgets.QWidget(self.stressVitalSign)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 50, 161, 101))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.RichText)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.RichText)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.layoutWidget5 = QtWidgets.QWidget(self.stressVitalSign)
        self.layoutWidget5.setGeometry(QtCore.QRect(170, 50, 171, 101))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.BBP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.BBP.setObjectName("BBP")
        self.gridLayout.addWidget(self.BBP, 0, 0, 1, 1)
        self.BHR = QtWidgets.QLineEdit(self.layoutWidget5)
        self.BHR.setObjectName("BHR")
        self.gridLayout.addWidget(self.BHR, 0, 1, 1, 1)
        self.DipDose = QtWidgets.QLineEdit(self.layoutWidget5)
        self.DipDose.setObjectName("DipDose")
        self.gridLayout.addWidget(self.DipDose, 1, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_19.setEnabled(False)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.ABP = QtWidgets.QLineEdit(self.layoutWidget5)
        self.ABP.setObjectName("ABP")
        self.gridLayout.addWidget(self.ABP, 2, 0, 1, 1)
        self.AHR = QtWidgets.QLineEdit(self.layoutWidget5)
        self.AHR.setObjectName("AHR")
        self.gridLayout.addWidget(self.AHR, 2, 1, 1, 1)
        self.qcBox = QtWidgets.QGroupBox(self.tab_2)
        self.qcBox.setGeometry(QtCore.QRect(10, 160, 741, 141))
        self.qcBox.setObjectName("qcBox")
        self.label_25 = QtWidgets.QLabel(self.qcBox)
        self.label_25.setGeometry(QtCore.QRect(10, 60, 291, 25))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.layoutWidget6 = QtWidgets.QWidget(self.qcBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 351, 27))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.SQC = QtWidgets.QComboBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.SQC.setFont(font)
        self.SQC.setObjectName("SQC")
        self.SQC.addItem("")
        self.SQC.addItem("")
        self.SQC.addItem("")
        self.horizontalLayout.addWidget(self.SQC)
        self.RQC = QtWidgets.QComboBox(self.layoutWidget6)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.RQC.setFont(font)
        self.RQC.setObjectName("RQC")
        self.RQC.addItem("")
        self.RQC.addItem("")
        self.RQC.addItem("")
        self.horizontalLayout.addWidget(self.RQC)
        self.layoutWidget7 = QtWidgets.QWidget(self.qcBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(140, 10, 211, 21))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.layoutWidget8 = QtWidgets.QWidget(self.qcBox)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 90, 379, 22))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_3.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.checkBox_27.setFont(font)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_3.addWidget(self.checkBox_27)
        self.checkBox_23 = QtWidgets.QCheckBox(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_3.addWidget(self.checkBox_23)
        self.layoutWidget9 = QtWidgets.QWidget(self.qcBox)
        self.layoutWidget9.setGeometry(QtCore.QRect(390, 90, 246, 22))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_22 = QtWidgets.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_4.addWidget(self.checkBox_22)
        self.checkBox_24 = QtWidgets.QCheckBox(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_4.addWidget(self.checkBox_24)
        self.layoutWidget10 = QtWidgets.QWidget(self.qcBox)
        self.layoutWidget10.setGeometry(QtCore.QRect(370, 30, 251, 27))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.TechQC = QtWidgets.QComboBox(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.TechQC.setFont(font)
        self.TechQC.setObjectName("TechQC")
        self.TechQC.addItem("")
        self.TechQC.addItem("")
        self.TechQC.addItem("")
        self.horizontalLayout_5.addWidget(self.TechQC)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_25.raise_()
        self.flowStatusBox = QtWidgets.QGroupBox(self.tab_2)
        self.flowStatusBox.setGeometry(QtCore.QRect(10, 300, 351, 211))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.flowStatusBox.setFont(font)
        self.flowStatusBox.setObjectName("flowStatusBox")
        self.layoutWidget11 = QtWidgets.QWidget(self.flowStatusBox)
        self.layoutWidget11.setGeometry(QtCore.QRect(10, 40, 45, 151))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_5.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_5.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_5.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.layoutWidget12 = QtWidgets.QWidget(self.flowStatusBox)
        self.layoutWidget12.setGeometry(QtCore.QRect(60, 40, 203, 151))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.LADStatus = QtWidgets.QComboBox(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LADStatus.setFont(font)
        self.LADStatus.setObjectName("LADStatus")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.LADStatus.addItem("")
        self.verticalLayout_6.addWidget(self.LADStatus)
        self.LCXStatus = QtWidgets.QComboBox(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LCXStatus.setFont(font)
        self.LCXStatus.setObjectName("LCXStatus")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.LCXStatus.addItem("")
        self.verticalLayout_6.addWidget(self.LCXStatus)
        self.RCAStatus = QtWidgets.QComboBox(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RCAStatus.setFont(font)
        self.RCAStatus.setObjectName("RCAStatus")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.RCAStatus.addItem("")
        self.verticalLayout_6.addWidget(self.RCAStatus)
        self.LVStatus = QtWidgets.QComboBox(self.layoutWidget12)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LVStatus.setFont(font)
        self.LVStatus.setObjectName("LVStatus")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.LVStatus.addItem("")
        self.verticalLayout_6.addWidget(self.LVStatus)
        self.layoutWidget13 = QtWidgets.QWidget(self.flowStatusBox)
        self.layoutWidget13.setGeometry(QtCore.QRect(270, 40, 71, 151))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LADArea = QtWidgets.QLineEdit(self.layoutWidget13)
        self.LADArea.setObjectName("LADArea")
        self.verticalLayout_7.addWidget(self.LADArea)
        self.LCXArea = QtWidgets.QLineEdit(self.layoutWidget13)
        self.LCXArea.setObjectName("LCXArea")
        self.verticalLayout_7.addWidget(self.LCXArea)
        self.RCAArea = QtWidgets.QLineEdit(self.layoutWidget13)
        self.RCAArea.setObjectName("RCAArea")
        self.verticalLayout_7.addWidget(self.RCAArea)
        self.LVArea = QtWidgets.QLineEdit(self.layoutWidget13)
        self.LVArea.setObjectName("LVArea")
        self.verticalLayout_7.addWidget(self.LVArea)
        self.mdFlowBox = QtWidgets.QGroupBox(self.tab_2)
        self.mdFlowBox.setGeometry(QtCore.QRect(380, 309, 361, 111))
        self.mdFlowBox.setObjectName("mdFlowBox")
        self.label_30 = QtWidgets.QLabel(self.mdFlowBox)
        self.label_30.setGeometry(QtCore.QRect(40, 20, 291, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.MDFStatus = QtWidgets.QComboBox(self.mdFlowBox)
        self.MDFStatus.setGeometry(QtCore.QRect(40, 50, 201, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MDFStatus.setFont(font)
        self.MDFStatus.setObjectName("MDFStatus")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFStatus.addItem("")
        self.MDFArea = QtWidgets.QLineEdit(self.mdFlowBox)
        self.MDFArea.setGeometry(QtCore.QRect(260, 50, 61, 31))
        self.MDFArea.setObjectName("MDFArea")
        self.MBFQClean = QtWidgets.QPushButton(self.tab_2)
        self.MBFQClean.setGeometry(QtCore.QRect(440, 450, 91, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MBFQClean.setFont(font)
        self.MBFQClean.setObjectName("MBFQClean")
        self.MBFQSend = QtWidgets.QPushButton(self.tab_2)
        self.MBFQSend.setGeometry(QtCore.QRect(580, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MBFQSend.setFont(font)
        self.MBFQSend.setObjectName("MBFQSend")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 111, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 111, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.patInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.patInfo.setGeometry(QtCore.QRect(109, -10, 651, 31))
        self.patInfo.setObjectName("patInfo")
        self.DM = QtWidgets.QCheckBox(self.patInfo)
        self.DM.setGeometry(QtCore.QRect(70, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.DM.setFont(font)
        self.DM.setObjectName("DM")
        self.FamilyHistory = QtWidgets.QCheckBox(self.patInfo)
        self.FamilyHistory.setGeometry(QtCore.QRect(120, 10, 131, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.FamilyHistory.setFont(font)
        self.FamilyHistory.setObjectName("FamilyHistory")
        self.checkBox_15 = QtWidgets.QCheckBox(self.patInfo)
        self.checkBox_15.setGeometry(QtCore.QRect(450, 10, 121, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.HTN = QtWidgets.QCheckBox(self.patInfo)
        self.HTN.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.HTN.setFont(font)
        self.HTN.setObjectName("HTN")
        self.checkBox_14 = QtWidgets.QCheckBox(self.patInfo)
        self.checkBox_14.setGeometry(QtCore.QRect(370, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_13 = QtWidgets.QCheckBox(self.patInfo)
        self.checkBox_13.setGeometry(QtCore.QRect(240, 10, 131, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.label_4 = QtWidgets.QLabel(self.patInfo)
        self.label_4.setGeometry(QtCore.QRect(610, 10, 21, 16))
        self.label_4.setObjectName("label_4")
        self.PTCA_year = QtWidgets.QLineEdit(self.patInfo)
        self.PTCA_year.setGeometry(QtCore.QRect(570, 10, 31, 21))
        self.PTCA_year.setObjectName("PTCA_year")
        self.patCc = QtWidgets.QGroupBox(self.centralwidget)
        self.patCc.setGeometry(QtCore.QRect(110, 20, 651, 31))
        self.patCc.setTitle("")
        self.patCc.setObjectName("patCc")
        self.checkBox_19 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_19.setGeometry(QtCore.QRect(340, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_17 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_17.setGeometry(QtCore.QRect(180, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_16 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 10, 171, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_21 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_21.setGeometry(QtCore.QRect(520, 10, 111, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_20 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_20.setGeometry(QtCore.QRect(430, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_18 = QtWidgets.QCheckBox(self.patCc)
        self.checkBox_18.setGeometry(QtCore.QRect(260, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(14)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.StatusBar = QtWidgets.QLabel(self.centralwidget)
        self.StatusBar.setGeometry(QtCore.QRect(14, 670, 371, 20))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.StatusBar.setFont(font)
        self.StatusBar.setText("")
        self.StatusBar.setObjectName("StatusBar")
        self.layoutWidget14 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget14.setGeometry(QtCore.QRect(398, 666, 351, 25))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RBox = QtWidgets.QComboBox(self.layoutWidget14)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.RBox.setFont(font)
        self.RBox.setObjectName("RBox")
        self.RBox.addItem("")
        self.RBox.addItem("")
        self.RBox.addItem("")
        self.RBox.addItem("")
        self.RBox.addItem("")
        self.horizontalLayout_6.addWidget(self.RBox)
        self.VBox = QtWidgets.QComboBox(self.layoutWidget14)
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(12)
        self.VBox.setFont(font)
        self.VBox.setObjectName("VBox")
        self.VBox.addItem("")
        self.VBox.addItem("")
        self.VBox.addItem("")
        self.VBox.addItem("")
        self.VBox.addItem("")
        self.horizontalLayout_6.addWidget(self.VBox)
        self.Sign = QtWidgets.QPushButton(self.layoutWidget14)
        self.Sign.setObjectName("Sign")
        self.horizontalLayout_6.addWidget(self.Sign)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 21))
        self.menubar.setObjectName("menubar")
        self.menuPatient_Info = QtWidgets.QMenu(self.menubar)
        self.menuPatient_Info.setObjectName("menuPatient_Info")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHypertension = QtWidgets.QAction(MainWindow)
        self.actionHypertension.setObjectName("actionHypertension")
        self.actionDM = QtWidgets.QAction(MainWindow)
        self.actionDM.setObjectName("actionDM")
        self.actionDyslipidemia = QtWidgets.QAction(MainWindow)
        self.actionDyslipidemia.setObjectName("actionDyslipidemia")
        self.actionFamily_history = QtWidgets.QAction(MainWindow)
        self.actionFamily_history.setObjectName("actionFamily_history")
        self.actionBradycardia = QtWidgets.QAction(MainWindow)
        self.actionBradycardia.setObjectName("actionBradycardia")
        self.actionMPI_2 = QtWidgets.QAction(MainWindow)
        self.actionMPI_2.setObjectName("actionMPI_2")
        self.actionMBFQ = QtWidgets.QAction(MainWindow)
        self.actionMBFQ.setObjectName("actionMBFQ")
        self.menuPatient_Info.addAction(self.actionMPI_2)
        self.menuPatient_Info.addAction(self.actionMBFQ)
        self.menubar.addAction(self.menuPatient_Info.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupDeep.setTitle(_translate("MainWindow", "GroupBox"))
        self.apical.setText(_translate("MainWindow", "apical"))
        self.mid.setText(_translate("MainWindow", "mid"))
        self.basal.setText(_translate("MainWindow", "basal"))
        self.groupStatus.setTitle(_translate("MainWindow", "GroupStatus"))
        self.Reversible.setText(_translate("MainWindow", "Reversible"))
        self.Partial.setText(_translate("MainWindow", "Partial reversible"))
        self.Irreversible.setText(_translate("MainWindow", "Irreversible"))
        self.RR.setText(_translate("MainWindow", "Reverse redistribution"))
        self.Attenuation.setText(_translate("MainWindow", "Attenuation"))
        self.Hypokinesia.setText(_translate("MainWindow", "Hypokinesia"))
        self.Addlesion.setText(_translate("MainWindow", "Add lesion"))
        self.CleanL.setText(_translate("MainWindow", "Clean"))
        self.groupStatus_2.setTitle(_translate("MainWindow", "GroupStatus"))
        self.label_ant.setText(_translate("MainWindow", "Anterior wall"))
        self.label_sep.setText(_translate("MainWindow", "Septal wall"))
        self.label_inf.setText(_translate("MainWindow", "Inferior wall"))
        self.label_lat.setText(_translate("MainWindow", "Lateral wall"))
        self.label_ap.setText(_translate("MainWindow", "Apical wall"))
        self.Ant.setCurrentText(_translate("MainWindow", "Normal uptake"))
        self.Ant.setItemText(0, _translate("MainWindow", "Normal uptake"))
        self.Ant.setItemText(1, _translate("MainWindow", "Reversible"))
        self.Ant.setItemText(2, _translate("MainWindow", "Partial reversible"))
        self.Ant.setItemText(3, _translate("MainWindow", "Irreversible"))
        self.Ant.setItemText(4, _translate("MainWindow", "Reverse redistribution"))
        self.Sep.setCurrentText(_translate("MainWindow", "Normal uptake"))
        self.Sep.setItemText(0, _translate("MainWindow", "Normal uptake"))
        self.Sep.setItemText(1, _translate("MainWindow", "Reversible"))
        self.Sep.setItemText(2, _translate("MainWindow", "Partial reversible"))
        self.Sep.setItemText(3, _translate("MainWindow", "Irreversible"))
        self.Sep.setItemText(4, _translate("MainWindow", "Reverse redistribution"))
        self.Inf.setCurrentText(_translate("MainWindow", "Normal uptake"))
        self.Inf.setItemText(0, _translate("MainWindow", "Normal uptake"))
        self.Inf.setItemText(1, _translate("MainWindow", "Reversible"))
        self.Inf.setItemText(2, _translate("MainWindow", "Partial reversible"))
        self.Inf.setItemText(3, _translate("MainWindow", "Irreversible"))
        self.Inf.setItemText(4, _translate("MainWindow", "Reverse redistribution"))
        self.Lat.setCurrentText(_translate("MainWindow", "Normal uptake"))
        self.Lat.setItemText(0, _translate("MainWindow", "Normal uptake"))
        self.Lat.setItemText(1, _translate("MainWindow", "Reversible"))
        self.Lat.setItemText(2, _translate("MainWindow", "Partial reversible"))
        self.Lat.setItemText(3, _translate("MainWindow", "Irreversible"))
        self.Lat.setItemText(4, _translate("MainWindow", "Reverse redistribution"))
        self.AP.setCurrentText(_translate("MainWindow", "Normal uptake"))
        self.AP.setItemText(0, _translate("MainWindow", "Normal uptake"))
        self.AP.setItemText(1, _translate("MainWindow", "Reversible"))
        self.AP.setItemText(2, _translate("MainWindow", "Partial reversible"))
        self.AP.setItemText(3, _translate("MainWindow", "Irreversible"))
        self.AP.setItemText(4, _translate("MainWindow", "Reverse redistribution"))
        self.groupFun.setTitle(_translate("MainWindow", "GroupBox"))
        self.Tl201.setText(_translate("MainWindow", "Tl-201"))
        self.MiBi.setText(_translate("MainWindow", "Tc-99m sestamibi"))
        self.label_7.setText(_translate("MainWindow", "LVEF"))
        self.label_8.setText(_translate("MainWindow", "L/H ratio"))
        self.label_9.setText(_translate("MainWindow", "Ischemia extent"))
        self.label_10.setText(_translate("MainWindow", "Stress"))
        self.label_11.setText(_translate("MainWindow", "Rest"))
        self.label_12.setText(_translate("MainWindow", "TID"))
        self.LVD.setText(_translate("MainWindow", "LV dilatation"))
        self.AddF.setText(_translate("MainWindow", "Add function"))
        self.CleanA.setText(_translate("MainWindow", "Clean"))
        self.Load.setText(_translate("MainWindow", "Load"))
        self.Send.setText(_translate("MainWindow", "Send"))
        self.groupWall.setTitle(_translate("MainWindow", "GroupWall"))
        self.checkBox_6.setText(_translate("MainWindow", "AL"))
        self.checkBox_10.setText(_translate("MainWindow", "AS"))
        self.checkBox_11.setText(_translate("MainWindow", "Sep"))
        self.checkBox_4.setText(_translate("MainWindow", "AP"))
        self.checkBox_7.setText(_translate("MainWindow", "Lat"))
        self.checkBox_9.setText(_translate("MainWindow", "Inf"))
        self.checkBox_8.setText(_translate("MainWindow", "IL"))
        self.checkBox_12.setText(_translate("MainWindow", "IS"))
        self.checkBox_5.setText(_translate("MainWindow", "Ant"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "MPI"))
        self.tracerDose.setTitle(_translate("MainWindow", "TracerDose"))
        self.BW.setText(_translate("MainWindow", "0"))
        self.RMibiDose.setText(_translate("MainWindow", "10"))
        self.RRMibiDose.setText(_translate("MainWindow", "0"))
        self.SMibiDose.setText(_translate("MainWindow", "30"))
        self.RSMibiDose.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Body Weight"))
        self.label_6.setText(_translate("MainWindow", "Rest Tc99m Mibi dose"))
        self.label_13.setText(_translate("MainWindow", "Stress Tc99m Mibi dose"))
        self.label_14.setText(_translate("MainWindow", "Residual Dose"))
        self.label_15.setText(_translate("MainWindow", "Residual Dose"))
        self.label_16.setText(_translate("MainWindow", "Kg"))
        self.stressVitalSign.setTitle(_translate("MainWindow", "StressStatus"))
        self.label_22.setText(_translate("MainWindow", "BP"))
        self.label_23.setText(_translate("MainWindow", "HR"))
        self.label_21.setText(_translate("MainWindow", "Before Administed"))
        self.label_17.setText(_translate("MainWindow", "Dipyridamole dose"))
        self.label_18.setText(_translate("MainWindow", "After Administed"))
        self.qcBox.setTitle(_translate("MainWindow", "QCBox"))
        self.label_25.setText(_translate("MainWindow", "The patient has developed side effect:"))
        self.label_19.setText(_translate("MainWindow", "Study Quality"))
        self.SQC.setItemText(0, _translate("MainWindow", "Excellent"))
        self.SQC.setItemText(1, _translate("MainWindow", "Acceptable"))
        self.SQC.setItemText(2, _translate("MainWindow", "Failed"))
        self.RQC.setItemText(0, _translate("MainWindow", "Excellent"))
        self.RQC.setItemText(1, _translate("MainWindow", "Acceptable"))
        self.RQC.setItemText(2, _translate("MainWindow", "Failed"))
        self.label_20.setText(_translate("MainWindow", "Stress"))
        self.label_24.setText(_translate("MainWindow", "Rest"))
        self.checkBox_26.setText(_translate("MainWindow", "Chest tightness or pain"))
        self.checkBox_27.setText(_translate("MainWindow", "Dyspnea"))
        self.checkBox_23.setText(_translate("MainWindow", "Dizziness"))
        self.checkBox_22.setText(_translate("MainWindow", "Abdominal pain"))
        self.checkBox_24.setText(_translate("MainWindow", "Palpitation"))
        self.label_31.setText(_translate("MainWindow", "Technical Issues:"))
        self.TechQC.setItemText(0, _translate("MainWindow", "Excellent"))
        self.TechQC.setItemText(1, _translate("MainWindow", "Acceptable"))
        self.TechQC.setItemText(2, _translate("MainWindow", "Failed"))
        self.flowStatusBox.setTitle(_translate("MainWindow", "FlowStatusBox"))
        self.label_26.setText(_translate("MainWindow", "LAD"))
        self.label_27.setText(_translate("MainWindow", "LCX"))
        self.label_28.setText(_translate("MainWindow", "RCA"))
        self.label_29.setText(_translate("MainWindow", "LV"))
        self.LADStatus.setItemText(0, _translate("MainWindow", "Normal"))
        self.LADStatus.setItemText(1, _translate("MainWindow", "Mild abnormal"))
        self.LADStatus.setItemText(2, _translate("MainWindow", "Moderate abnormal"))
        self.LADStatus.setItemText(3, _translate("MainWindow", "Ischemia"))
        self.LADStatus.setItemText(4, _translate("MainWindow", "Severe ischemia"))
        self.LADStatus.setItemText(5, _translate("MainWindow", "Steal"))
        self.LADStatus.setItemText(6, _translate("MainWindow", "Infarction"))
        self.LCXStatus.setItemText(0, _translate("MainWindow", "Normal"))
        self.LCXStatus.setItemText(1, _translate("MainWindow", "Mild abnormal"))
        self.LCXStatus.setItemText(2, _translate("MainWindow", "Moderate abnormal"))
        self.LCXStatus.setItemText(3, _translate("MainWindow", "Ischemia"))
        self.LCXStatus.setItemText(4, _translate("MainWindow", "Severe ischemia"))
        self.LCXStatus.setItemText(5, _translate("MainWindow", "Steal"))
        self.LCXStatus.setItemText(6, _translate("MainWindow", "Infarction"))
        self.RCAStatus.setItemText(0, _translate("MainWindow", "Normal"))
        self.RCAStatus.setItemText(1, _translate("MainWindow", "Mild abnormal"))
        self.RCAStatus.setItemText(2, _translate("MainWindow", "Moderate abnormal"))
        self.RCAStatus.setItemText(3, _translate("MainWindow", "Ischemia"))
        self.RCAStatus.setItemText(4, _translate("MainWindow", "Severe ischemia"))
        self.RCAStatus.setItemText(5, _translate("MainWindow", "Steal"))
        self.RCAStatus.setItemText(6, _translate("MainWindow", "Infarction"))
        self.LVStatus.setItemText(0, _translate("MainWindow", "Normal"))
        self.LVStatus.setItemText(1, _translate("MainWindow", "Mild abnormal"))
        self.LVStatus.setItemText(2, _translate("MainWindow", "Moderate abnormal"))
        self.LVStatus.setItemText(3, _translate("MainWindow", "Ischemia"))
        self.LVStatus.setItemText(4, _translate("MainWindow", "Severe ischemia"))
        self.LVStatus.setItemText(5, _translate("MainWindow", "Steal"))
        self.LVStatus.setItemText(6, _translate("MainWindow", "Infarction"))
        self.mdFlowBox.setTitle(_translate("MainWindow", "MDflowBox"))
        self.label_30.setText(_translate("MainWindow", "The most degraded flow status"))
        self.MDFStatus.setItemText(0, _translate("MainWindow", "Normal"))
        self.MDFStatus.setItemText(1, _translate("MainWindow", "Mild abnormal"))
        self.MDFStatus.setItemText(2, _translate("MainWindow", "Moderate abnormal"))
        self.MDFStatus.setItemText(3, _translate("MainWindow", "Ischemia"))
        self.MDFStatus.setItemText(4, _translate("MainWindow", "Severe ischemia"))
        self.MDFStatus.setItemText(5, _translate("MainWindow", "Steal"))
        self.MDFStatus.setItemText(6, _translate("MainWindow", "Infarction"))
        self.MBFQClean.setText(_translate("MainWindow", "Clean"))
        self.MBFQSend.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "MBFQ"))
        self.label_2.setText(_translate("MainWindow", "Patient History"))
        self.label_3.setText(_translate("MainWindow", "Chief complaint"))
        self.patInfo.setTitle(_translate("MainWindow", "GroupBox"))
        self.DM.setText(_translate("MainWindow", "DM"))
        self.FamilyHistory.setText(_translate("MainWindow", "family CAD history"))
        self.checkBox_15.setText(_translate("MainWindow", "CAD s/p PTCA"))
        self.HTN.setText(_translate("MainWindow", "HTN"))
        self.checkBox_14.setText(_translate("MainWindow", "CAD"))
        self.checkBox_13.setText(_translate("MainWindow", "high cholesterol"))
        self.label_4.setText(_translate("MainWindow", "Ago"))
        self.checkBox_19.setText(_translate("MainWindow", "palpitation"))
        self.checkBox_17.setText(_translate("MainWindow", "dyspnea"))
        self.checkBox_16.setText(_translate("MainWindow", "chest tightness or pain"))
        self.checkBox_21.setText(_translate("MainWindow", "cold sweating"))
        self.checkBox_20.setText(_translate("MainWindow", "headache"))
        self.checkBox_18.setText(_translate("MainWindow", "syncope"))
        self.RBox.setItemText(0, _translate("MainWindow", "Non"))
        self.RBox.setItemText(1, _translate("MainWindow", "陳世緯"))
        self.RBox.setItemText(2, _translate("MainWindow", "林聖哲"))
        self.RBox.setItemText(3, _translate("MainWindow", "蘇奕鴒"))
        self.RBox.setItemText(4, _translate("MainWindow", "周慧姍"))
        self.VBox.setItemText(0, _translate("MainWindow", "Non"))
        self.VBox.setItemText(1, _translate("MainWindow", "陳遠光"))
        self.VBox.setItemText(2, _translate("MainWindow", "沈業有"))
        self.VBox.setItemText(3, _translate("MainWindow", "葉加祿"))
        self.VBox.setItemText(4, _translate("MainWindow", "陳世緯"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.menuPatient_Info.setTitle(_translate("MainWindow", "設定"))
        self.actionHypertension.setText(_translate("MainWindow", "Hypertension"))
        self.actionDM.setText(_translate("MainWindow", "DM"))
        self.actionDyslipidemia.setText(_translate("MainWindow", "Dyslipidemia"))
        self.actionFamily_history.setText(_translate("MainWindow", "Family history"))
        self.actionBradycardia.setText(_translate("MainWindow", "Bradycardia"))
        self.actionMPI_2.setText(_translate("MainWindow", "MPI格式"))
        self.actionMBFQ.setText(_translate("MainWindow", "MBFQ格式"))

